apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app-insert-data
  name: app-insert-data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-insert-data
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app-insert-data
    spec:
      containers:
        - args:
            - python
            - -m
            - src.utils.insert_mongodb
          image: app-insert-data
          name: app-insert-data
          resources: {}
      restartPolicy: Always
status: {}
